#ifndef DT_STUDY_IP_APPS_HPP
#define DT_STUDY_IP_APPS_HPP
#include "csv-logger.hpp"
#include "dt-state.hpp"
#include "experiment-config.hpp"
#include "wire-format.hpp"
#include "ns3/core-module.h"
#include "ns3/internet-module.h"
#include "ns3/network-module.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <memory>
#include <stdexcept>
#include <string>
namespace dtstudy {
class DtUdpServer:public ns3::Application{
public:static ns3::TypeId GetTypeId(){static ns3::TypeId tid=ns3::TypeId("dtstudy::DtUdpServer").SetParent<ns3::Application>().AddConstructor<DtUdpServer>();return tid;}
void Configure(uint16_t p,std::shared_ptr<PhysicalStateModel>s,uint32_t b){m_port=p;m_stateModel=s;m_payloadBytes=b;}
protected:void StartApplication()override{m_socket=ns3::Socket::CreateSocket(GetNode(),ns3::UdpSocketFactory::GetTypeId());if(m_socket->Bind(ns3::InetSocketAddress(ns3::Ipv4Address::GetAny(),m_port))!=0)throw std::runtime_error("DtUdpServer: Bind failed");m_socket->SetRecvCallback(ns3::MakeCallback(&DtUdpServer::HandleRead,this));}void StopApplication()override{if(m_socket){m_socket->Close();m_socket=nullptr;}}
private:void HandleRead(ns3::Ptr<ns3::Socket>socket){ns3::Address from;while(ns3::Ptr<ns3::Packet>packet=socket->RecvFrom(from)){std::string payload(packet->GetSize(),'\0');if(!payload.empty())packet->CopyData(reinterpret_cast<uint8_t*>(&payload[0]),payload.size());uint64_t id=0;uint32_t f=0;if(!DecodeIpRequest(payload,id,f))continue;const DtState&state=m_stateModel->GetLatestSnapshot();const std::string response=EncodeIpResponse(id,state,m_payloadBytes);auto reply=ns3::Create<ns3::Packet>(reinterpret_cast<const uint8_t*>(response.data()),response.size());socket->SendTo(reply,0,from);}}uint16_t m_port=9000;std::shared_ptr<PhysicalStateModel>m_stateModel;uint32_t m_payloadBytes=512;ns3::Ptr<ns3::Socket>m_socket;};

class DtUdpClient:public ns3::Application{
public:static ns3::TypeId GetTypeId(){static ns3::TypeId tid=ns3::TypeId("dtstudy::DtUdpClient").SetParent<ns3::Application>().AddConstructor<DtUdpClient>();return tid;}
void Configure(const std::string&name,ns3::Ipv4Address addr,uint16_t port,uint32_t fmax,double rate,double jitter,uint32_t timeout,uint32_t run,const std::string&exp,std::shared_ptr<PhysicalStateModel>state,std::shared_ptr<CsvLogger>logger,uint32_t salt,double measurementStart,uint32_t offset){m_consumerName=name;m_serverAddress=addr;m_serverPort=port;m_fmaxMs=fmax;m_requestRateHz=rate;m_requestJitterMs=jitter;m_requestTimeoutMs=timeout;m_run=run;m_experiment=exp;m_stateModel=state;m_logger=logger;m_consumerSalt=salt;m_requestJitter=ns3::CreateObject<ns3::UniformRandomVariable>();m_requestJitter->SetStream(static_cast<int64_t>(salt));m_measurementStartS=measurementStart;m_firstRequestOffsetMs=offset;}
protected:void StartApplication()override{m_socket=ns3::Socket::CreateSocket(GetNode(),ns3::UdpSocketFactory::GetTypeId());m_socket->Bind();m_socket->SetRecvCallback(ns3::MakeCallback(&DtUdpClient::HandleRead,this));m_sendEvent=ns3::Simulator::Schedule(ns3::MilliSeconds(m_firstRequestOffsetMs),&DtUdpClient::SendRequest,this);}void StopApplication()override{if(m_sendEvent.IsRunning())ns3::Simulator::Cancel(m_sendEvent);if(m_timeoutEvent.IsRunning())ns3::Simulator::Cancel(m_timeoutEvent);if(m_socket){m_socket->Close();m_socket=nullptr;}}
private:bool InWindow(uint64_t us)const{return us>=static_cast<uint64_t>(m_measurementStartS*1e6);}double NextInterval(){const double base=m_requestRateHz>0?1.0/m_requestRateHz:1.0;if(m_requestJitterMs<=0||!m_requestJitter)return base;return std::max(0.001,base+m_requestJitter->GetValue(-m_requestJitterMs,m_requestJitterMs)/1000.0);}
void SendRequest(){const double interval=NextInterval();m_sendEvent=ns3::Simulator::Schedule(ns3::Seconds(interval),&DtUdpClient::SendRequest,this);NS_ABORT_MSG_IF(m_outstanding,"DtUdpClient invariant violated: requestTimeoutMs must be below minimum request interval.");++m_nextRequestId;m_lastRequestId=m_nextRequestId;m_lastSendUs=static_cast<uint64_t>(ns3::Simulator::Now().GetMicroSeconds());m_outstanding=true;const std::string req=EncodeIpRequest(m_lastRequestId,m_fmaxMs);auto packet=ns3::Create<ns3::Packet>(reinterpret_cast<const uint8_t*>(req.data()),req.size());if(InWindow(m_lastSendUs)){OfferedRequestRecord o;o.run=m_run;o.arm="A";o.approachName=ArmToApproachName(Arm::IP);o.experiment=m_experiment;o.consumer=m_consumerName;o.requestId=m_lastRequestId;o.fmaxMs=m_fmaxMs;o.sendTimeUs=m_lastSendUs;o.transport="IPv4-UDP";m_logger->LogOfferedRequest(o);}m_socket->SendTo(packet,0,ns3::InetSocketAddress(m_serverAddress,m_serverPort));m_timeoutEvent=ns3::Simulator::Schedule(ns3::MilliSeconds(m_requestTimeoutMs),&DtUdpClient::HandleTimeout,this,m_lastRequestId,m_lastSendUs);}
void HandleTimeout(uint64_t id,uint64_t sendUs){if(!m_outstanding||id!=m_lastRequestId)return;if(InWindow(sendUs)){TimeoutRecord t;t.run=m_run;t.arm="A";t.approachName=ArmToApproachName(Arm::IP);t.experiment=m_experiment;t.consumer=m_consumerName;t.requestId=id;t.sendTimeUs=sendUs;t.timeoutTimeUs=static_cast<uint64_t>(ns3::Simulator::Now().GetMicroSeconds());t.transport="IPv4-UDP";m_logger->LogTimeout(t);}m_outstanding=false;}
void HandleRead(ns3::Ptr<ns3::Socket>socket){ns3::Address from;while(ns3::Ptr<ns3::Packet>packet=socket->RecvFrom(from)){std::string payload(packet->GetSize(),'\0');if(!payload.empty())packet->CopyData(reinterpret_cast<uint8_t*>(&payload[0]),payload.size());uint64_t id=0;DtState state;if(!DecodeIpResponse(payload,id,state))continue;if(!m_outstanding||id!=m_lastRequestId)continue;if(m_timeoutEvent.IsRunning())ns3::Simulator::Cancel(m_timeoutEvent);const uint64_t nowUs=static_cast<uint64_t>(ns3::Simulator::Now().GetMicroSeconds());const double latency=static_cast<double>(nowUs-m_lastSendUs)/1000.0;const double aoi=nowUs>=state.generationTimeUs?static_cast<double>(nowUs-state.generationTimeUs)/1000.0:0.0;const auto truth=m_stateModel->GetTruthAt(ns3::Simulator::Now());const double dx=truth.first-state.x,dy=truth.second-state.y;if(InWindow(m_lastSendUs)){RequestRecord r;r.run=m_run;r.arm="A";r.approachName=ArmToApproachName(Arm::IP);r.experiment=m_experiment;r.simTimeS=ns3::Simulator::Now().GetSeconds();r.consumer=m_consumerName;r.requestId=id;r.fmaxMs=m_fmaxMs;r.sendTimeUs=m_lastSendUs;r.receiveTimeUs=nowUs;r.latencyMs=latency;r.generationTimeUs=state.generationTimeUs;r.aoiMs=aoi;r.stateVersion=state.version;r.stateX=state.x;r.stateY=state.y;r.truthX=truth.first;r.truthY=truth.second;r.dtError=std::sqrt(dx*dx+dy*dy);r.freshnessValid=aoi<=m_fmaxMs;r.transport="IPv4-UDP";m_logger->LogRequest(r);}m_outstanding=false;}}
std::string m_consumerName="consumer";ns3::Ipv4Address m_serverAddress;uint16_t m_serverPort=9000;uint32_t m_fmaxMs=100;double m_requestRateHz=10,m_requestJitterMs=0;uint32_t m_requestTimeoutMs=80,m_run=1;std::string m_experiment="e1";std::shared_ptr<PhysicalStateModel>m_stateModel;std::shared_ptr<CsvLogger>m_logger;uint32_t m_consumerSalt=1;ns3::Ptr<ns3::UniformRandomVariable>m_requestJitter;double m_measurementStartS=0;uint32_t m_firstRequestOffsetMs=100;uint64_t m_nextRequestId=0,m_lastRequestId=0,m_lastSendUs=0;bool m_outstanding=false;ns3::Ptr<ns3::Socket>m_socket;ns3::EventId m_sendEvent,m_timeoutEvent;};
} // namespace dtstudy
#endif
