#ifndef DT_STUDY_NDN_APPS_HPP
#define DT_STUDY_NDN_APPS_HPP
#include "csv-logger.hpp"
#include "dt-state.hpp"
#include "experiment-config.hpp"
#include "wire-format.hpp"
#include "ns3/core-module.h"
#include "ns3/ndnSIM-module.h"
#include "ns3/ndnSIM/apps/ndn-app.hpp"
#include "ns3/ndnSIM/helper/ndn-fib-helper.hpp"
#include "ns3/ndnSIM/helper/ndn-stack-helper.hpp"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <memory>
#include <string>
namespace dtstudy {
inline uint32_t NonceToUint32(const ::ndn::Interest::Nonce&n){return(static_cast<uint32_t>(n[0])<<24)|(static_cast<uint32_t>(n[1])<<16)|(static_cast<uint32_t>(n[2])<<8)|static_cast<uint32_t>(n[3]);}
class DtNdnProducer:public ns3::ndn::App{public:static ns3::TypeId GetTypeId(){static ns3::TypeId tid=ns3::TypeId("dtstudy::DtNdnProducer").SetParent<ns3::ndn::App>().AddConstructor<DtNdnProducer>();return tid;}void Configure(const std::string&p,std::shared_ptr<PhysicalStateModel>s,uint32_t f,uint32_t b){m_prefix=p;m_stateModel=s;m_nativeFreshnessMs=f;m_payloadBytes=b;}void StartApplication()override{ns3::ndn::App::StartApplication();ns3::ndn::FibHelper::AddRoute(GetNode(),m_prefix,m_face,0);}void StopApplication()override{ns3::ndn::App::StopApplication();}void OnInterest(std::shared_ptr<const::ndn::Interest>interest)override{ns3::ndn::App::OnInterest(interest);if(!m_stateModel)return;const DtState&state=m_stateModel->GetLatestSnapshot();const std::string payload=EncodeState(state,m_payloadBytes);auto data=std::make_shared<::ndn::Data>(interest->getName());data->setFreshnessPeriod(::ndn::time::milliseconds(m_nativeFreshnessMs));data->setContent(std::make_shared<::ndn::Buffer>(payload.begin(),payload.end()));ns3::ndn::StackHelper::getKeyChain().sign(*data);m_transmittedDatas(data,this,m_face);m_appLink->onReceiveData(*data);}private:std::string m_prefix="/dt/robot27/state";std::shared_ptr<PhysicalStateModel>m_stateModel;uint32_t m_nativeFreshnessMs=500,m_payloadBytes=512;};
class DtNdnConsumer:public ns3::ndn::App{
public:static ns3::TypeId GetTypeId(){static ns3::TypeId tid=ns3::TypeId("dtstudy::DtNdnConsumer").SetParent<ns3::ndn::App>().AddConstructor<DtNdnConsumer>();return tid;}
void Configure(const std::string&name,const std::string&prefix,Arm arm,uint32_t fmax,double rate,double jitter,uint32_t timeout,uint32_t run,const std::string&exp,std::shared_ptr<PhysicalStateModel>state,std::shared_ptr<CsvLogger>logger,uint32_t salt,double measurementStart,uint32_t offset){m_consumerName=name;m_prefix=prefix;m_arm=arm;m_fmaxMs=fmax;m_requestRateHz=rate;m_requestJitterMs=jitter;m_requestTimeoutMs=timeout;m_run=run;m_experiment=exp;m_stateModel=state;m_logger=logger;m_consumerSalt=salt;m_requestJitter=ns3::CreateObject<ns3::UniformRandomVariable>();m_requestJitter->SetStream(static_cast<int64_t>(salt));m_measurementStartS=measurementStart;m_firstRequestOffsetMs=offset;}
void StartApplication()override{ns3::ndn::App::StartApplication();m_sendEvent=ns3::Simulator::Schedule(ns3::MilliSeconds(m_firstRequestOffsetMs),&DtNdnConsumer::SendInterest,this);}void StopApplication()override{if(m_sendEvent.IsRunning())ns3::Simulator::Cancel(m_sendEvent);if(m_timeoutEvent.IsRunning())ns3::Simulator::Cancel(m_timeoutEvent);ns3::ndn::App::StopApplication();}
void OnData(std::shared_ptr<const::ndn::Data>data)override{ns3::ndn::App::OnData(data);if(!m_outstanding)return;if(m_timeoutEvent.IsRunning())ns3::Simulator::Cancel(m_timeoutEvent);const::ndn::Block&content=data->getContent();const std::string payload(reinterpret_cast<const char*>(content.value()),content.value_size());DtState state;if(!DecodeState(payload,state)){m_outstanding=false;return;}const uint64_t nowUs=static_cast<uint64_t>(ns3::Simulator::Now().GetMicroSeconds());const double latency=static_cast<double>(nowUs-m_lastSendUs)/1000.0;const double aoi=nowUs>=state.generationTimeUs?static_cast<double>(nowUs-state.generationTimeUs)/1000.0:0.0;const auto truth=m_stateModel->GetTruthAt(ns3::Simulator::Now());const double dx=truth.first-state.x,dy=truth.second-state.y;if(InWindow(m_lastSendUs)){RequestRecord r;r.run=m_run;r.arm=ArmToString(m_arm);r.approachName=ArmToApproachName(m_arm);r.experiment=m_experiment;r.simTimeS=ns3::Simulator::Now().GetSeconds();r.consumer=m_consumerName;r.requestId=m_lastRequestId;r.interestNonce=m_lastNonce;r.fmaxMs=m_fmaxMs;r.sendTimeUs=m_lastSendUs;r.receiveTimeUs=nowUs;r.latencyMs=latency;r.generationTimeUs=state.generationTimeUs;r.aoiMs=aoi;r.stateVersion=state.version;r.stateX=state.x;r.stateY=state.y;r.truthX=truth.first;r.truthY=truth.second;r.dtError=std::sqrt(dx*dx+dy*dy);r.freshnessValid=aoi<=m_fmaxMs;r.transport="NDN";m_logger->LogRequest(r);}m_outstanding=false;}
private:bool InWindow(uint64_t us)const{return us>=static_cast<uint64_t>(m_measurementStartS*1e6);}double NextInterval(){const double base=m_requestRateHz>0?1.0/m_requestRateHz:1.0;if(m_requestJitterMs<=0||!m_requestJitter)return base;return std::max(0.001,base+m_requestJitter->GetValue(-m_requestJitterMs,m_requestJitterMs)/1000.0);}
void SendInterest(){const double interval=NextInterval();m_sendEvent=ns3::Simulator::Schedule(ns3::Seconds(interval),&DtNdnConsumer::SendInterest,this);NS_ABORT_MSG_IF(m_outstanding,"DtNdnConsumer invariant violated: requestTimeoutMs must be below minimum request interval.");++m_nextRequestId;auto interest=std::make_shared<::ndn::Interest>(::ndn::Name(m_prefix));interest->setCanBePrefix(false);interest->setInterestLifetime(::ndn::time::milliseconds(m_requestTimeoutMs));if(m_arm==Arm::NDN_NATIVE){interest->setMustBeFresh(true);interest->setNonce(EncodeOrdinaryNonce(m_nextRequestId,m_consumerSalt));}else if(m_arm==Arm::NDN_FRESHNESS_AWARE){interest->setMustBeFresh(false);interest->setNonce(EncodeFreshnessAwareNonce(m_fmaxMs,m_nextRequestId,m_consumerSalt));}else{interest->setMustBeFresh(false);interest->setNonce(EncodeOrdinaryNonce(m_nextRequestId,m_consumerSalt));}m_lastRequestId=m_nextRequestId;m_lastNonce=NonceToUint32(interest->getNonce());m_lastSendUs=static_cast<uint64_t>(ns3::Simulator::Now().GetMicroSeconds());m_outstanding=true;if(InWindow(m_lastSendUs)){OfferedRequestRecord o;o.run=m_run;o.arm=ArmToString(m_arm);o.approachName=ArmToApproachName(m_arm);o.experiment=m_experiment;o.consumer=m_consumerName;o.requestId=m_lastRequestId;o.interestNonce=m_lastNonce;o.fmaxMs=m_fmaxMs;o.sendTimeUs=m_lastSendUs;o.transport="NDN";m_logger->LogOfferedRequest(o);}m_transmittedInterests(interest,this,m_face);m_appLink->onReceiveInterest(*interest);m_timeoutEvent=ns3::Simulator::Schedule(ns3::MilliSeconds(m_requestTimeoutMs),&DtNdnConsumer::HandleTimeout,this,m_lastRequestId,m_lastNonce,m_lastSendUs);}
void HandleTimeout(uint64_t id,uint32_t nonce,uint64_t sendUs){if(!m_outstanding||id!=m_lastRequestId)return;if(InWindow(sendUs)){TimeoutRecord t;t.run=m_run;t.arm=ArmToString(m_arm);t.approachName=ArmToApproachName(m_arm);t.experiment=m_experiment;t.consumer=m_consumerName;t.requestId=id;t.interestNonce=nonce;t.sendTimeUs=sendUs;t.timeoutTimeUs=static_cast<uint64_t>(ns3::Simulator::Now().GetMicroSeconds());t.transport="NDN";m_logger->LogTimeout(t);}m_outstanding=false;}
std::string m_consumerName="consumer",m_prefix="/dt/robot27/state";Arm m_arm=Arm::NDN_NATIVE;uint32_t m_fmaxMs=100;double m_requestRateHz=10,m_requestJitterMs=0;uint32_t m_requestTimeoutMs=80,m_run=1;std::string m_experiment="e1";std::shared_ptr<PhysicalStateModel>m_stateModel;std::shared_ptr<CsvLogger>m_logger;uint32_t m_consumerSalt=1;ns3::Ptr<ns3::UniformRandomVariable>m_requestJitter;double m_measurementStartS=0;uint32_t m_firstRequestOffsetMs=100;uint64_t m_nextRequestId=0,m_lastRequestId=0,m_lastSendUs=0;uint32_t m_lastNonce=0;bool m_outstanding=false;ns3::EventId m_sendEvent,m_timeoutEvent;};
} // namespace dtstudy
#endif
